### ISSUE TITLE
Eigen3 Warning on Kinetic

### ISSUE THREAD

**Issue by davetcoleman** [ros-perception/slam_karto#12]
```
Warnings   << slam_karto:cmake /home/dave/ros/current/ws_moveit/logs/slam_karto/build.cmake.003.log                                                       
CMake Warning at /opt/ros/kinetic/share/cmake_modules/cmake/Modules/FindEigen.cmake:62 (message):
  The FindEigen.cmake Module in the cmake_modules package is deprecated.

  Please use the FindEigen3.cmake Module provided with Eigen.  Change
  instances of find_package(Eigen) to find_package(Eigen3).  Check the
  FindEigen3.cmake Module for the resulting CMake variable names.

Call Stack (most recent call first):
  CMakeLists.txt:17 (find_package)
```

**Comment by WENJIAN0629** [comment]
[ INFO] [1495075422.804255281, 1494847537.362521814]: laser laser's pose wrt base: 0.150 0.000 0.000
Registering sensor: [laser]
[ INFO] [1495075900.451681132, 1494848015.006153533]: Calling doSPA for loop closure
[slam_karto-2] process has died [pid 15130, exit code -11, cmd /home/wenjian/catkin_ws/devel/lib/slam_karto/slam_karto scan:=scan __name:=slam_karto __log:=/home/wenjian/.ros/log/75dfcdca-3b66-11e7-9eb8-6c71d964baf6/slam_karto-2.log].
log file: /home/wenjian/.ros/log/75dfcdca-3b66-11e7-9eb8-6c71d964baf6/slam_karto-2*.log

**Comment by mikeferguson** [comment]
Fixed in Melodic.
