### ISSUE TITLE
sample data of slam_karto

### ISSUE THREAD

**Issue by sgzzgit** [ros-perception/slam_karto#16]
I run slam_karto under ubuntu14.04  ros indigo with one LMS111 Lidar. But could not achieve the map.
Now my data consist of laser data only. Is the odometry data necessary? 
Could you share a link of the demo data?

**Comment by mikeferguson** [comment]
Odometry is required. I've heard of people using the things like http://wiki.ros.org/laser_scan_matcher, but have never myself.

There really aren't "demo data" provided by anyone in particular. Two options are to look at a simulated robot, or maybe a bag file from someone. I have several (very old) bag files with smaller lasers and odometry over here: http://wiki.ros.org/laser_scan_matcher

P.S. questions like this really belong on answers.ros.org -- not as tickets.

**Comment by sgzzgit** [comment]
Thanks for your answer
