### ISSUE TITLE
Does Karto Support Mapping In the Outdoor Environment With One 2D laser scanner?

### ISSUE THREAD

**Issue by sgzzgit** [ros-perception/slam_karto#17]
Sorry for bother you again.
I want to do mapping in the urban environment which has a lot of big trees and buildings. But from my experiment result. The mapping of Karto in outdoor environment is not good.
I am wandering why.  Is Karto able to do mapping in the outdoor environment? 
Thanks in advance.

**Comment by mikeferguson** [comment]
These sort of questions really belong on ROS answers
