### ISSUE TITLE
Aborted (core dumped) after "Finished doSPA for loop closure"

### ISSUE THREAD

**Issue by Shayens** [ros-perception/slam_karto#27]
After "Finished doSPA for loop closure", 
it shows "terminate called after throwing an instance of 'std::length_error' what(): basic_string::_M_create
Aborted (core dumped)"
I have already change “Eigen” to "Eigen3" both in slam_karto and sparse_bundle_adjestment CMake files.
Does anybody has some ideas? Thx

**Comment by mikeferguson** [comment]
Pretty sure https://github.com/ros-perception/sparse_bundle_adjustment/pull/10 will fix this (the variable was uninitialized, seems to sometimes cause us to do cholmod. Cholmod seems to cause segfaults).
