### ISSUE TITLE
how to expand the area of the blue area(dont know how to define the name)

### ISSUE THREAD

**Issue by ZOUJIASHUAI** [ros-perception/slam_karto#31]
I used two bag with different laser to feed the karto,one the max distance is 30m , another is 65m,and the rviz shows the different area that 30m laser get 22m*22m area and 65m laser only get 11m*13m area,so can you tell me how to expand the area? 

my laser topic is 

 frame_id: "laser"
angle_min: -2.35619449615
angle_max: 2.35619449615
angle_increment: 0.00174532923847
time_increment: 0.0
scan_time: 0.0399999991059
range_min: 0.0010000000475
range_max: 65.0

  frame_id: "laser"
angle_min: 0.0
angle_max: 6.28318548203
angle_increment: 0.00174581410829
time_increment: 0.0
scan_time: 0.0500000007451
range_min: 0.0
range_max: 30.0

**Comment by ZOUJIASHUAI** [comment]
![2020-06-30 17-04-24 的屏幕截图](https://user-images.githubusercontent.com/19969444/86110925-c059fc80-baf8-11ea-9604-f621a031b59f.png)

**Comment by ZOUJIASHUAI** [comment]
![2020-06-30 17-04-57 的屏幕截图](https://user-images.githubusercontent.com/19969444/86110986-d5cf2680-baf8-11ea-9c0c-08c32486d70a.png)

**Comment by mikeferguson** [comment]
There really isn't a parameter for this - it's buried deep inside Karto. Once you start moving around, the map should start to expand as you add more scans.

**Comment by ZOUJIASHUAI** [comment]
> There really isn't a parameter for this - it's buried deep inside Karto. Once you start moving around, the map should start to expand as you add more scans.

thank you for your reply , I know when I start moving the map will expand,but when I use 65m laser to mapping,the localization and the mapping result is much worse than a 30m laser,It looks like the original recognize area is smaller than 30m laser(very strange),and since the area is very small there's a lot of laser point are not been recognize by karto.so different laser have different recognize area and the shorter laser have a big recognize area. so I wander if I can expand that area or what  leads to two laser have different area.
that is how I describe the recognize area hope you can understand

**Comment by mikeferguson** [comment]
You could try setting "scan_buffer_maximum_scan_distance" parameter - it defaults to 20.0.

In your images above - the laser has nothing to do with the different map size. The map size is different because of what the lasers are seeing. If you were to place the two lasers in the exact same location, you will get nearly identical map sizes. In both cases, the map range reading used is the 20m default based on the previously mentioned parameter.
