### ISSUE TITLE
Can't locate slam_karto node, probable error in building

### ISSUE THREAD

**Issue by PedromsLeal** [ros-perception/slam_karto#35]
After having cloned slam_karto and open_karto from ros-perception into my catkin_ws/src, and done catkin_make, i couldn't run karto as it couldn't locate the slam_karto node.
The paste catkin_ws/devel/lib/slam_karto is empty, could it be an error in building? I'm using ros noetic.

**Comment by mikeferguson** [comment]
Debian builds are working, so I think this is a workspace issue. Closing since this is an ancient ticket.
