### ISSUE TITLE
Has the upside-down laser detection fix (#5) been released?

### ISSUE THREAD

**Issue by spmaniato** [ros-perception/slam_karto#6]
@mgerdzhev @jonbinney @mikeferguson Has the fix in #5 made it to release?

I'm in ROS Indigo and installed the `slam_karto` Debian package. I'm getting the "laser is mounted upside-down" message (and a correspondingly flipped map) even though my laser is straight.

Here's an rviz screenshot and I have some more info below:

![laser_not_inverted](https://cloud.githubusercontent.com/assets/2285973/12829140/87b70fe4-cb56-11e5-8318-d3b892dd68f7.png)

Another reason I'm suspecting I don't have the latest `slam_karto` is that I don't see this ([L373](https://github.com/ros-perception/slam_karto/blob/indigo-devel/src/slam_karto.cpp#L373)):

``` cpp
ROS_DEBUG("Z-Axis in sensor frame: %.3f", up.z());
```

when I set the verbosity level to `DEBUG`. This message was introduced in #5.

**Comment by jonbinney** [comment]
Looks like that hasn't been released yet. Most recent indigo release was 0.7.2 in july. (I don't think slam_karto has been released into jade at all).

**Comment by spmaniato** [comment]
Roger, thanks! 

Also, I just confirmed by building `slam_karto` from source. All good now that #5 is definitely in.

**Comment by jonbinney** [comment]
@mikeferguson do you have time to do a release?

**Comment by mikeferguson** [comment]
https://github.com/ros/rosdistro/pull/10429
