### ISSUE TITLE
Always publishing this warning

### ISSUE THREAD

**Issue by somebodyus** [ros-perception/slam_karto#8]
Always publishing this warning:
Failed to compute odom pose, skipping scan (Lookup would require extrapolation into the future.

**Comment by spmaniato** [comment]
This sounds like a `tf` configuration issue. I recommend that you ask on [ROS Answers](http://answers.ros.org/questions/) first, including some info on your TF frames, etc. in your question.

**Comment by lucbettaieb** [comment]
Agreed, I've never gotten that error before while using slam_karto.  I'd post on ROS Answers with your tf tree included.  You can use `rqt_tf_tree`.

**Comment by mikeferguson** [comment]
Consensus is that this should be on ROS answers, going to close
